# Generated by Django 5.1.2 on 2024-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="temp", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
