# Generated by Django 5.1.2 on 2024-10-28 15:48

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("write_date", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("전체", "전체"),
                            ("자유게시판", "자유게시판"),
                            ("질문게시판", "질문게시판"),
                            ("토론게시판", "토론게시판"),
                            ("정보게시판", "정보게시판"),
                        ]
                    ),
                ),
                ("content", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("write_date", models.DateTimeField()),
                ("content", models.TextField()),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="myboard.posting",
                    ),
                ),
            ],
        ),
    ]
