# Generated by Django 5.1.2 on 2024-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="category",
            field=models.CharField(
                choices=[
                    ("전체", "전체"),
                    ("자유게시판", "자유게시판"),
                    ("취업정보", "취업정보"),
                    ("자소서공유", "자소서공유"),
                    ("정보", "정보"),
                ]
            ),
        ),
    ]
