# Generated by Django 5.1.2 on 2024-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="content",
            field=models.TextField(unique=True),
        ),
    ]
