# Generated by Django 5.1.2 on 2024-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("writer", models.CharField()),
                ("write_date", models.DateTimeField()),
                ("category", models.CharField()),
                ("content", models.TextField()),
                ("key_word", models.JSONField(default=list)),
                ("url", models.URLField()),
            ],
        ),
    ]
