# Generated by Django 5.1.2 on 2024-10-26 17:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mynews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
