# Generated by Django 5.1.2 on 2024-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynews", "0003_remove_preference_user_id_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
